name: Deploy API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --build-arg PORT=${{ secrets.PORT }} --build-arg MONGO_URL=${{ secrets.MONGO_URL }} --build-arg JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} --build-arg SEEDER_EMAIL=${{ secrets.SEEDER_EMAIL }} --build-arg SEEDER_PASSWORD=${{ secrets.SEEDER_PASSWORD }} --build-arg SEEDER_PHONENUMBER=${{ secrets.SEEDER_PHONENUMBER }} --build-arg WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} --build-arg RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} --build-arg RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} --build-arg MapMyIndiaAPIKey=${{ secrets.MapMyIndiaAPIKey }} --build-arg MAPPLS_CLIENT_ID=${{ secrets.MAPPLS_CLIENT_ID }} --build-arg MAPPLS_CLIENT_SECRET=${{ secrets.MAPPLS_CLIENT_SECRET }} --build-arg API_KEY=${{ secrets.API_KEY }} --build-arg AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} --build-arg PROJECT_ID=${{ secrets.PROJECT_ID }} --build-arg STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} --build-arg MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} --build-arg APP_ID=${{ secrets.APP_ID }} --build-arg MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }} -t myfamto/famto-api:latest .
          docker push myfamto/famto-api:latest

      - name: Deploy to DigitalOcean Droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull myfamto/famto-api:latest
            docker stop famto_api_container || true
            docker rm famto_api_container || true
            docker run -d --name famto_api_container \
              -p 80:5000 \
              -e PORT=${{ secrets.PORT }} \
              -e MONGO_URL=${{ secrets.MONGO_URL }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e SEEDER_EMAIL=${{ secrets.SEEDER_EMAIL }} \
              -e SEEDER_PASSWORD=${{ secrets.SEEDER_PASSWORD }} \
              -e SEEDER_PHONENUMBER=${{ secrets.SEEDER_PHONENUMBER }} \
              -e WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} \
              -e RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} \
              -e RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} \
              -e MapMyIndiaAPIKey=${{ secrets.MapMyIndiaAPIKey }} \
              -e MAPPLS_CLIENT_ID=${{ secrets.MAPPLS_CLIENT_ID }} \
              -e MAPPLS_CLIENT_SECRET=${{ secrets.MAPPLS_CLIENT_SECRET }} \
              -e API_KEY=${{ secrets.API_KEY }} \
              -e AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} \
              -e PROJECT_ID=${{ secrets.PROJECT_ID }} \
              -e STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} \
              -e MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} \
              -e APP_ID=${{ secrets.APP_ID }} \
              -e MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }} \
              myfamto/famto-api:latest
